name: Extract and Analyze APK

on:
  push:
    branches:
      - main

jobs:
  extract_and_analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install unrar
        run: sudo apt-get install unrar

      - name: Extract RAR files
        run: |
          unrar x -o+ net.easypark.android_12300_apps.evozi.com.apk.part1.rar
          #unrar x -o+ net.easypark.android_12300_apps.evozi.com.apk.part2.rar

      - name: Install APKTool
        run: |
          wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
          wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.5.0.jar
          chmod +x apktool
          sudo mv apktool /usr/local/bin/
          sudo mv apktool_2.5.0.jar /usr/local/bin/

      - name: Decompile APK files
        run: java -jar /usr/local/bin/apktool_2.5.0.jar d net.easypark.android_12300_apps.evozi.com.apk -f -o out_folder

      - name: Check for links, APIs, and keys
        run: |
          search_dir="out_folder"
          result_file="found_items.txt"
          grep -r -n -E '(https?://[^ ]+|API_KEY|SECRET_KEY|ACCESS_KEY)' "$search_dir" > "$result_file"
          if [ ! -s "$result_file" ]; then
              echo "No links, APIs, or keys found."
          else
              echo "Found items:"
              cat "$result_file"
          fi

      - name: Commit and push analysis results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Added analysis results"
          git push
